"""introspection-scaling — see README."""

from introspection_scaling.extract import (
    BASELINE_WORDS,
    CONCEPT_WORDS,
    ConceptVector,
    build_dataset,
    extract_concept_vector,
    load_extraction_model,
    make_random_matched,
)
from introspection_scaling.harness import (
    DEPTH_FRACTION_DEFAULT,
    DOSE_FRACTION_CEILING,
    DOSE_FRACTION_DEFAULT,
    AnthropicJudge,
    BedrockJudge,
    Completion,
    ConceptVectorLike,
    Condition,
    ConditionRate,
    DoseGenerator,
    JudgeVerdict,
    MissingJudgeCredentialsError,
    RepengGenerator,
    RuleBasedJudge,
    TrialRecord,
    aggregate,
    build_prompt,
    dose_alpha,
    generate_completions,
    generate_concept_completions,
    judge_completions,
    layer_for_fraction,
    make_judge,
    render_prompt,
    run_concept,
    run_conditions,
    to_seed_records,
    trial_sampling_seed,
    write_seed_records,
)

__version__ = "0.0.1"

__all__ = [
    "BASELINE_WORDS",
    "CONCEPT_WORDS",
    "DEPTH_FRACTION_DEFAULT",
    "DOSE_FRACTION_CEILING",
    "DOSE_FRACTION_DEFAULT",
    "AnthropicJudge",
    "BedrockJudge",
    "Completion",
    "ConceptVector",
    "ConceptVectorLike",
    "Condition",
    "ConditionRate",
    "DoseGenerator",
    "JudgeVerdict",
    "MissingJudgeCredentialsError",
    "RepengGenerator",
    "RuleBasedJudge",
    "TrialRecord",
    "__version__",
    "aggregate",
    "build_dataset",
    "build_prompt",
    "dose_alpha",
    "extract_concept_vector",
    "generate_completions",
    "generate_concept_completions",
    "judge_completions",
    "layer_for_fraction",
    "load_extraction_model",
    "make_judge",
    "make_random_matched",
    "render_prompt",
    "run_concept",
    "run_conditions",
    "to_seed_records",
    "trial_sampling_seed",
    "write_seed_records",
]
